@dictit_api_HostAddress = http://localhost:5261

GET {{dictit_api_HostAddress}}/search/ass
Accept: application/json

###

GET {{dictit_api_HostAddress}}/search/helloasdfsfeesf
Accept: application/json

###

GET {{dictit_api_HostAddress}}/saved-words/33199900-1589-4f1a-9321-005a252b40ef
Content-Type: application/json
Accept: application/json

###

POST {{dictit_api_HostAddress}}/saved-words
Content-Type: application/json
Accept: application/json

{
  "Word": "huge",
  "UserId": "33199900-1589-4f1a-9321-005a252b40ef"
}